CREATE TABLE "tbl_transaction_item" (
  "id" SERIAL PRIMARY KEY,
  "transaction_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "quantiy" INTEGER NOT NULL,
  "price" DECIMAL(10, 2) NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
